#!/usr/bin/env -S uv run --script

# /// script
# requires-python = ">=3.14"
# dependencies = []
# ///

"""PreToolUse hook: validates conventional commit format on `git commit`.

Inspects bash commands for `git commit` invocations carrying `-m` or
`--message`. Extracts each message value (handling simple quoting and
the `"$(cat <<TAG ... TAG)"` heredoc form used by this codebase) and
validates the first non-empty line against the project's commit
conventions.

Pass-through cases (exit 0):
- Non-Bash tools, empty or non-`git commit` commands.
- `git commit` with no `-m`/`--message`. The editor opens; we have no
  message to inspect, so we trust the user.
- `--fixup` / `--squash` flags. Git auto-generates the message.
- Messages whose first line is auto-generated by git itself: prefixes
  `Merge `, `Revert "`, `Revert '`, `fixup!`, `squash!`, `amend!`.

Validation rules (first match blocks with exit 2):
- `empty-subject`: message is empty after stripping.
- `header-too-long`: first line > 70 characters.
- `bad-format`: first line does not match `<type>(<scope>): <subject>`
  where type is lowercase letters, scope is optional, and an optional
  `!` may precede the colon to mark a breaking change.
- `bad-type`: type is not in the allowed list.
- `subject-wip-marker`: subject starts with `wip`, `[wip]`, `draft`,
  `[draft]`, or `(draft)` (case-insensitive).
- `subject-uppercase`: subject's first character is uppercase.
- `subject-trailing-whitespace`: subject ends with a space or tab.
- `subject-trailing-period`: subject ends with a period.
- `subject-trailing-punctuation`: subject ends with `!` or `?`.
- `subject-not-imperative`: subject's first word is a known past-tense,
  gerund, or third-person form (curated `NON_IMPERATIVE_VERBS` table).
"""

from __future__ import annotations

import json
import re
import sys
from dataclasses import dataclass

ALLOWED_TYPES: tuple[str, ...] = (
    "build",
    "ci",
    "docs",
    "feat",
    "fix",
    "perf",
    "refactor",
    "style",
    "test",
)

MAX_HEADER_LEN = 70

# First-word denylist for imperative-mood enforcement. Maps a known
# non-imperative form (past tense, gerund, or third-person singular) to
# its imperative root, used in the violation suggestion. Curated rather
# than algorithmic so we never block valid imperatives that happen to
# end in -ed/-ing/-s ("release", "pass", "address", "feed", "bring").
# Extend when a real false-negative escapes; suffix heuristics produce
# noisier blocks than the imperative rule deters.
NON_IMPERATIVE_VERBS: dict[str, str] = {
    "added": "add",
    "adding": "add",
    "adds": "add",
    "amended": "amend",
    "amending": "amend",
    "amends": "amend",
    "appended": "append",
    "appending": "append",
    "appends": "append",
    "applied": "apply",
    "applying": "apply",
    "applies": "apply",
    "batched": "batch",
    "batching": "batch",
    "batches": "batch",
    "blocked": "block",
    "blocking": "block",
    "blocks": "block",
    "built": "build",
    "building": "build",
    "builds": "build",
    "bumped": "bump",
    "bumping": "bump",
    "bumps": "bump",
    "changed": "change",
    "changing": "change",
    "changes": "change",
    "cleaned": "clean",
    "cleaning": "clean",
    "cleans": "clean",
    "commits": "commit",
    "committing": "commit",
    "consolidated": "consolidate",
    "consolidating": "consolidate",
    "consolidates": "consolidate",
    "converted": "convert",
    "converting": "convert",
    "converts": "convert",
    "copied": "copy",
    "copying": "copy",
    "copies": "copy",
    "created": "create",
    "creating": "create",
    "creates": "create",
    "decreased": "decrease",
    "decreases": "decrease",
    "decreasing": "decrease",
    "deleted": "delete",
    "deletes": "delete",
    "deleting": "delete",
    "deprecated": "deprecate",
    "deprecates": "deprecate",
    "deprecating": "deprecate",
    "dropped": "drop",
    "dropping": "drop",
    "drops": "drop",
    "enforced": "enforce",
    "enforces": "enforce",
    "enforcing": "enforce",
    "enhanced": "enhance",
    "enhances": "enhance",
    "enhancing": "enhance",
    "extracted": "extract",
    "extracting": "extract",
    "extracts": "extract",
    "fixed": "fix",
    "fixes": "fix",
    "fixing": "fix",
    "gathered": "gather",
    "gathering": "gather",
    "gathers": "gather",
    "generated": "generate",
    "generates": "generate",
    "generating": "generate",
    "grouped": "group",
    "grouping": "group",
    "groups": "group",
    "implemented": "implement",
    "implementing": "implement",
    "increased": "increase",
    "increases": "increase",
    "increasing": "increase",
    "implements": "implement",
    "injected": "inject",
    "injecting": "inject",
    "injects": "inject",
    "improved": "improve",
    "improves": "improve",
    "improving": "improve",
    "initialized": "initialize",
    "initializes": "initialize",
    "initializing": "initialize",
    "introduced": "introduce",
    "introduces": "introduce",
    "introducing": "introduce",
    "made": "make",
    "making": "make",
    "makes": "make",
    "merged": "merge",
    "merging": "merge",
    "merges": "merge",
    "migrated": "migrate",
    "migrates": "migrate",
    "migrating": "migrate",
    "moved": "move",
    "moves": "move",
    "moving": "move",
    "optimized": "optimize",
    "optimizes": "optimize",
    "optimizing": "optimize",
    "passed": "pass",
    "passing": "pass",
    "passes": "pass",
    "ported": "port",
    "porting": "port",
    "ports": "port",
    "redesigned": "redesign",
    "redesigning": "redesign",
    "redesigns": "redesign",
    "refactored": "refactor",
    "refactoring": "refactor",
    "refactors": "refactor",
    "removed": "remove",
    "removing": "remove",
    "removes": "remove",
    "renamed": "rename",
    "renaming": "rename",
    "renames": "rename",
    "rendered": "render",
    "rendering": "render",
    "renders": "render",
    "replaced": "replace",
    "replacing": "replace",
    "replaces": "replace",
    "restored": "restore",
    "restoring": "restore",
    "restores": "restore",
    "reverted": "revert",
    "reverting": "revert",
    "reverts": "revert",
    "simplified": "simplify",
    "simplifying": "simplify",
    "simplifies": "simplify",
    "sorted": "sort",
    "sorting": "sort",
    "sorts": "sort",
    "squashed": "squash",
    "squashing": "squash",
    "squashes": "squash",
    "switched": "switch",
    "switching": "switch",
    "switches": "switch",
    "tweaked": "tweak",
    "tweaking": "tweak",
    "tweaks": "tweak",
    "updated": "update",
    "updating": "update",
    "updates": "update",
    "used": "use",
    "using": "use",
    "uses": "use",
    "verified": "verify",
    "verifying": "verify",
    "verifies": "verify",
    "wired": "wire",
    "wiring": "wire",
    "wires": "wire",
}

# Extracts the first word of the subject after stripping any leading
# non-word characters (so `"added"` and `(added)` resolve to `added`).
FIRST_WORD_RE = re.compile(r"\W*(\w+)")

# First-line prefixes that git auto-generates. We never validate these,
# even when the user is technically the one running `git commit -m`,
# because the content originates from git's merge/revert/fixup machinery
# and is not subject to project commit conventions.
AUTO_PREFIXES: tuple[str, ...] = (
    "Merge ",
    'Revert "',
    "Revert '",
    "fixup!",
    "squash!",
    "amend!",
)

# Header grammar: lowercase type, optional `(scope)`, optional `!`
# breaking-change marker, `: `, then subject.
HEADER_RE = re.compile(r"^(?P<type>[a-z]+)(?:\((?P<scope>[^)]*)\))?!?: (?P<subject>.+)$")

# Catches in-progress markers leaked into a subject. Mirrors
# crate-ci/committed's WIP regex; case-insensitive so `WIP`, `Wip`, and
# `wip` all match. The bracketed variants exist because some teams use
# `[WIP]` or `(Draft)` as conventional pull-request markers; either way
# they should not land on `main`.
WIP_MARKER_RE = re.compile(
    r"^(?:wip\b|\[wip\]|draft\b|\[draft\]|\(draft\))",
    re.IGNORECASE,
)

# Detects `git commit` as a likely command invocation. Allows interleaved
# `-c key=val` / `-C path` flags between `git` and `commit`. Not anchored
# to a command-start position, so substrings inside echoed strings can
# false-positive; in practice agents execute commits rather than echo
# them, and the cost of a spurious block is just a re-quoted message.
GIT_COMMIT_RE = re.compile(r"\bgit\s+(?:-[Cc]\s+\S+\s+)*commit\b")

# Single regex matching both message forms in source order:
# - Heredoc: -m "$(cat <<'TAG'\n...body...\nTAG\n)"
# - Quoted:  -m "..." or -m '...' or --message="..." etc.
#
# Heredoc is tried first inside the alternation so its `"$(...)"` cannot
# be misparsed as a degenerate empty double-quoted string. `(?<!\S)`
# ensures the flag starts at a token boundary so `--my-message` does
# not match.
M_VALUE_RE = re.compile(
    r"(?<!\S)(?:-[a-zA-Z]*m|--message(?:\s*=)?)\s*"
    r"(?:"
    r'"\$\(\s*cat\s*<<-?\s*[\'"]?(?P<tag>\w+)[\'"]?\s*\n'
    r"(?P<heredoc>.*?)\n(?P=tag)\s*\)\""
    r'|"(?P<dq>(?:\\.|[^"\\])*)"'
    r"|'(?P<sq>[^']*)'"
    r")",
    re.DOTALL,
)


@dataclass(frozen=True, slots=True)
class Violation:
    """A failed validation rule."""

    id: str
    reason: str


# Appended to every block message so the agent has the full format spec
# in front of it and can fix the message in one shot rather than chain
# through one violation at a time. The type list is rendered from
# `ALLOWED_TYPES` so the footer can never drift from the rule data.
FOOTER = (
    "\n\n"
    "Format: `<type>(<scope>)?[!]?: <subject>` (Angular Conventional Commits).\n"
    f"Types: {', '.join(ALLOWED_TYPES)}.\n"
    "Subject: lowercase imperative, <=70 chars, no trailing whitespace, period, `!`, or `?`.\n"
    "Full ruleset: invoke the `git-rules` skill."
)


def _first_message(cmd: str) -> str | None:
    """Pull the first `-m` / `--message` value out of a bash command.

    Only the first one matters for validation: git treats subsequent
    `-m` args as body paragraphs, which the project conventions do not
    constrain. Returns None if no recognizable message is present.
    """
    m = M_VALUE_RE.search(cmd)
    if m is None:
        return None
    if m.group("heredoc") is not None:
        return m.group("heredoc")
    if m.group("dq") is not None:
        return m.group("dq")
    return m.group("sq")


def _first_line(text: str) -> str:
    """Return the first non-empty stripped line, or empty string."""
    for line in text.splitlines():
        if line.strip():
            return line
    return ""


def _is_auto(line: str) -> bool:
    """True if this line is a git-auto-generated message we should skip."""
    return any(line.startswith(p) for p in AUTO_PREFIXES)


def _check_shape(line: str) -> Violation | re.Match[str]:
    """Check header emptiness, length, and grammar; return the parsed match on success."""
    if not line:
        return Violation("empty-subject", "commit message is empty")
    if len(line) > MAX_HEADER_LEN:
        return Violation(
            "header-too-long",
            f"first line is {len(line)} chars, must be <= {MAX_HEADER_LEN}",
        )
    m = HEADER_RE.match(line)
    if not m:
        return Violation(
            "bad-format",
            "header must match `<type>(<scope>): <subject>` (scope optional)",
        )
    return m


def _check_trailing(subject: str) -> Violation | None:
    """Block disallowed trailing characters on the subject."""
    last = subject[-1:]
    if last in (" ", "\t"):
        return Violation("subject-trailing-whitespace", "subject must not end with whitespace")
    if last == ".":
        return Violation("subject-trailing-period", "subject must not end with a period")
    if last in ("!", "?"):
        return Violation("subject-trailing-punctuation", f"subject must not end with {last!r}")
    return None


def _check_content(m: re.Match[str]) -> Violation | None:
    """Validate the parsed type and subject against the project rules.

    The WIP/Draft check runs before the lowercase-first-letter check so
    that `WIP add foo` produces the more specific marker message rather
    than `subject-uppercase`.
    """
    type_ = m.group("type")
    if type_ not in ALLOWED_TYPES:
        return Violation(
            "bad-type",
            f"type {type_!r} not allowed; use one of: " + ", ".join(ALLOWED_TYPES),
        )
    subject = m.group("subject")
    if WIP_MARKER_RE.match(subject):
        return Violation("subject-wip-marker", "subject must not start with a WIP/Draft marker")
    if subject[:1].isupper():
        return Violation("subject-uppercase", "subject must start with a lowercase letter")
    trailing = _check_trailing(subject)
    if trailing is not None:
        return trailing
    word_match = FIRST_WORD_RE.match(subject)
    first_word = word_match.group(1).lower() if word_match else ""
    if first_word in NON_IMPERATIVE_VERBS:
        return Violation(
            "subject-not-imperative",
            f"first word {first_word!r} is not imperative; "
            f"use {NON_IMPERATIVE_VERBS[first_word]!r}",
        )
    return None


def _validate(line: str) -> Violation | None:
    """Return the first violation against the rule list, or None."""
    shape = _check_shape(line)
    if isinstance(shape, Violation):
        return shape
    return _check_content(shape)


def _block(violation: Violation, line: str) -> None:
    """Emit a BLOCKED message and exit 2."""
    print(  # noqa: T201
        f"BLOCKED [{violation.id}]: {violation.reason}\n  first line: {line!r}{FOOTER}",
        file=sys.stderr,
    )
    sys.exit(2)


def main() -> None:
    """Entry point for the PreToolUse hook."""
    try:
        data = json.load(sys.stdin)
    except (json.JSONDecodeError, EOFError):
        sys.exit(0)

    if data.get("tool_name") != "Bash":
        sys.exit(0)

    cmd = (data.get("tool_input") or {}).get("command", "")
    if not cmd or not GIT_COMMIT_RE.search(cmd):
        sys.exit(0)

    # `--fixup` and `--squash` produce auto-prefixed messages even when
    # the user does not pass `-m`. Skip the whole invocation.
    if re.search(r"(?<!\S)(--fixup|--squash)\b", cmd):
        sys.exit(0)

    msg = _first_message(cmd)
    if msg is None:
        # No -m / --message found: editor opens or -F file is used. We
        # cannot see the message text, so we let it through.
        sys.exit(0)

    line = _first_line(msg)
    if _is_auto(line):
        sys.exit(0)

    violation = _validate(line)
    if violation is not None:
        _block(violation, line)

    sys.exit(0)


if __name__ == "__main__":
    main()
